;;;; lstm.lisp — Model 3: LSTM network implemented from scratch
;;;; Single LSTM layer (32 units) + dense output head, trained with
;;;; full-batch backpropagation-through-time and the Adam optimizer.
;;;; Lookback window: 3 months (matches the Assignment 2 design; the
;;;; two stacked layers of the write-up are reduced to one because the
;;;; real dataset is small, ~60 training samples).

(in-package :cpp4103)

(defun sigmoid (z) (/ 1d0 (+ 1d0 (exp (- (max -30d0 (min 30d0 z)))))))

(defstruct lstm
  d h            ; input dim, hidden units
  wg bg          ; gate weights (4H x (D+H)) and biases (4H) — rows [i f o g]
  v by           ; output head: weights (H), bias (scalar)
  ;; Adam state
  m-wg v-wg m-bg v-bg m-v v-v m-by v-by
  tstep)

(defun make-lstm-net (d h)
  (let* ((r (/ 1d0 (sqrt (float (+ d h) 1d0))))
         (wg (make-array (list (* 4 h) (+ d h)) :element-type 'double-float))
         (bg (make-array (* 4 h) :element-type 'double-float :initial-element 0d0))
         (v (make-array h :element-type 'double-float)))
    (dotimes (i (* 4 h))
      (dotimes (j (+ d h))
        (setf (aref wg i j) (rand-uniform (- r) r))))
    ;; forget-gate bias init to 1.0 (standard practice)
    (loop for i from h below (* 2 h) do (setf (aref bg i) 1d0))
    (dotimes (i h) (setf (aref v i) (rand-uniform (- r) r)))
    (make-lstm :d d :h h :wg wg :bg bg :v v :by 0d0
               :m-wg (make-array (list (* 4 h) (+ d h)) :element-type 'double-float :initial-element 0d0)
               :v-wg (make-array (list (* 4 h) (+ d h)) :element-type 'double-float :initial-element 0d0)
               :m-bg (make-array (* 4 h) :element-type 'double-float :initial-element 0d0)
               :v-bg (make-array (* 4 h) :element-type 'double-float :initial-element 0d0)
               :m-v (make-array h :element-type 'double-float :initial-element 0d0)
               :v-v (make-array h :element-type 'double-float :initial-element 0d0)
               :m-by 0d0 :v-by 0d0 :tstep 0)))

(defun lstm-forward (net seq)
  "SEQ: list of input vectors (length D each), T timesteps.
   Returns (values y-hat caches) where caches hold per-step activations."
  (let* ((d (lstm-d net)) (h (lstm-h net))
         (wg (lstm-wg net)) (bg (lstm-bg net))
         (hprev (make-array h :element-type 'double-float :initial-element 0d0))
         (cprev (make-array h :element-type 'double-float :initial-element 0d0))
         (caches '()))
    (dolist (x seq)
      (let ((xh (make-array (+ d h) :element-type 'double-float))
            (ig (make-array h :element-type 'double-float))
            (fg (make-array h :element-type 'double-float))
            (og (make-array h :element-type 'double-float))
            (gg (make-array h :element-type 'double-float))
            (c (make-array h :element-type 'double-float))
            (hv (make-array h :element-type 'double-float)))
        (dotimes (j d) (setf (aref xh j) (aref x j)))
        (dotimes (j h) (setf (aref xh (+ d j)) (aref hprev j)))
        (dotimes (u h)
          (flet ((zrow (row)
                   (let ((s (aref bg row)))
                     (dotimes (j (+ d h)) (incf s (* (aref wg row j) (aref xh j))))
                     s)))
            (setf (aref ig u) (sigmoid (zrow u))
                  (aref fg u) (sigmoid (zrow (+ h u)))
                  (aref og u) (sigmoid (zrow (+ (* 2 h) u)))
                  (aref gg u) (tanh (zrow (+ (* 3 h) u))))))
        (dotimes (u h)
          (setf (aref c u) (+ (* (aref fg u) (aref cprev u))
                              (* (aref ig u) (aref gg u))))
          (setf (aref hv u) (* (aref og u) (tanh (aref c u)))))
        (push (list :xh xh :i ig :f fg :o og :g gg :c c :h hv :cprev cprev) caches)
        (setf hprev hv cprev c)))
    (let ((y (lstm-by net)))
      (dotimes (u h) (incf y (* (aref (lstm-v net) u) (aref hprev u))))
      (values y (nreverse caches)))))

(defun lstm-backward (net caches dy grads)
  "Accumulate gradients for one sample into GRADS (plist of arrays).
   DY is dLoss/dy-hat."
  (let* ((d (lstm-d net)) (h (lstm-h net))
         (wg (lstm-wg net))
         (dwg (getf grads :wg)) (dbg (getf grads :bg))
         (dv (getf grads :v))
         (last-h (getf (car (last caches)) :h))
         (dh (make-array h :element-type 'double-float))
         (dc (make-array h :element-type 'double-float :initial-element 0d0)))
    ;; output head
    (dotimes (u h)
      (incf (aref dv u) (* dy (aref last-h u)))
      (setf (aref dh u) (* dy (aref (lstm-v net) u))))
    (incf (getf grads :by) dy)
    ;; through time
    (dolist (cache (reverse caches))
      (let* ((xh (getf cache :xh)) (ig (getf cache :i)) (fg (getf cache :f))
             (og (getf cache :o)) (gg (getf cache :g)) (c (getf cache :c))
             (cprev (getf cache :cprev))
             (dz (make-array (* 4 h) :element-type 'double-float))
             (dh-prev (make-array h :element-type 'double-float :initial-element 0d0))
             (dc-prev (make-array h :element-type 'double-float)))
        (dotimes (u h)
          (let* ((tc (tanh (aref c u)))
                 (do- (* (aref dh u) tc))
                 (dcu (+ (aref dc u) (* (aref dh u) (aref og u) (- 1d0 (* tc tc)))))
                 (di (* dcu (aref gg u)))
                 (df (* dcu (aref cprev u)))
                 (dg (* dcu (aref ig u))))
            (setf (aref dz u) (* di (aref ig u) (- 1d0 (aref ig u)))
                  (aref dz (+ h u)) (* df (aref fg u) (- 1d0 (aref fg u)))
                  (aref dz (+ (* 2 h) u)) (* do- (aref og u) (- 1d0 (aref og u)))
                  (aref dz (+ (* 3 h) u)) (* dg (- 1d0 (* (aref gg u) (aref gg u)))))
            (setf (aref dc-prev u) (* dcu (aref fg u)))))
        ;; parameter grads and upstream dh
        (dotimes (row (* 4 h))
          (let ((dzr (aref dz row)))
            (unless (zerop dzr)
              (dotimes (j (+ d h))
                (incf (aref dwg row j) (* dzr (aref xh j))))
              (incf (aref dbg row) dzr)
              (dotimes (j h)
                (incf (aref dh-prev j) (* dzr (aref wg row (+ d j))))))))
        (setf dh dh-prev dc dc-prev)))
    grads))

(defun adam-step! (param grad m v tstep lr &key (b1 0.9d0) (b2 0.999d0) (eps 1d-8))
  "In-place Adam update; PARAM/GRAD/M/V are congruent arrays."
  (let ((bc1 (- 1d0 (expt b1 tstep)))
        (bc2 (- 1d0 (expt b2 tstep))))
    (flet ((upd (g m-old v-old)
             (let* ((m-new (+ (* b1 m-old) (* (- 1d0 b1) g)))
                    (v-new (+ (* b2 v-old) (* (- 1d0 b2) g g)))
                    (delta (/ (* lr (/ m-new bc1))
                              (+ (sqrt (/ v-new bc2)) eps))))
               (values m-new v-new delta))))
      (if (= (array-rank param) 2)
          (dotimes (i (array-dimension param 0))
            (dotimes (j (array-dimension param 1))
              (multiple-value-bind (mn vn dl)
                  (upd (aref grad i j) (aref m i j) (aref v i j))
                (setf (aref m i j) mn (aref v i j) vn)
                (decf (aref param i j) dl))))
          (dotimes (i (length param))
            (multiple-value-bind (mn vn dl)
                (upd (aref grad i) (aref m i) (aref v i))
              (setf (aref m i) mn (aref v i) vn)
              (decf (aref param i) dl)))))))

(defun lstm-fit (sequences targets &key (h 32) (epochs 200) (lr 0.01d0) verbose)
  "SEQUENCES: list of samples, each a list of T input vectors.
   TARGETS: vector of standardized target values."
  (let* ((d (length (first (first sequences))))
         (net (make-lstm-net d h))
         (n (length sequences)))
    (dotimes (epoch epochs)
      (let ((dwg (make-array (list (* 4 h) (+ d h)) :element-type 'double-float :initial-element 0d0))
            (dbg (make-array (* 4 h) :element-type 'double-float :initial-element 0d0))
            (dv (make-array h :element-type 'double-float :initial-element 0d0))
            (loss 0d0))
        (let ((grads (list :wg dwg :bg dbg :v dv :by 0d0)))
          (loop for seq in sequences for k from 0 do
            (multiple-value-bind (yhat caches) (lstm-forward net seq)
              (let ((err (- yhat (aref targets k))))
                (incf loss (* err err))
                (setf grads (lstm-backward net caches (/ (* 2d0 err) n) grads)))))
          ;; average handled via dy scaling above; take Adam step
          (incf (lstm-tstep net))
          (let ((ts (lstm-tstep net)))
            (adam-step! (lstm-wg net) dwg (lstm-m-wg net) (lstm-v-wg net) ts lr)
            (adam-step! (lstm-bg net) dbg (lstm-m-bg net) (lstm-v-bg net) ts lr)
            (adam-step! (lstm-v net) dv (lstm-m-v net) (lstm-v-v net) ts lr)
            ;; scalar bias update (plain Adam inline)
            (let* ((g (getf grads :by))
                   (b1 0.9d0) (b2 0.999d0)
                   (mn (+ (* b1 (lstm-m-by net)) (* (- 1d0 b1) g)))
                   (vn (+ (* b2 (lstm-v-by net)) (* (- 1d0 b2) g g))))
              (setf (lstm-m-by net) mn (lstm-v-by net) vn)
              (decf (lstm-by net)
                    (/ (* lr (/ mn (- 1d0 (expt b1 ts))))
                       (+ (sqrt (/ vn (- 1d0 (expt b2 ts)))) 1d-8))))))
        (when (and verbose (zerop (mod (1+ epoch) 50)))
          (format t "      LSTM epoch ~3d  train MSE ~,5f~%" (1+ epoch) (/ loss n)))))
    net))

(defun lstm-predict (net sequences)
  (let ((out (make-array (length sequences) :element-type 'double-float)))
    (loop for seq in sequences for i from 0
          do (setf (aref out i) (lstm-forward net seq)))
    out))
